# fly.toml app configuration file generated for pixelpoint-co on 2024-01-16T16:12:48+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pixelpoint-co"
primary_region = "nrt"
swap_size_mb = 512

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/resources/healthcheck"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
